// 'use client'
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import './globals.css'
// import AuthProvider from "@/context/AuthProvider";
// import { Toaster } from "@/components/ui/toaster"
// import Navbar from "@/components/navbar";
// import { useEffect, useState } from "react";

// const inter = Inter({ subsets: ["latin"] });
// const [isClient, setIsClient] = useState(false)

// useEffect(() => {
//   setIsClient(true);
// }, []);

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       {
//         isClient && <AuthProvider>
//         <body className={inter.className}>
//           <Navbar />
//           {children}<Toaster />
//         </body>
//         </AuthProvider>
//       }
      
//     </html>
//   );
// }

'use client';

import { Inter } from "next/font/google";
import './globals.css';
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        {isClient ? (
          <AuthProvider>
            
            {children}
            <Toaster />
          </AuthProvider>
        ) : (
          // Optionally, you can add a loading spinner or placeholder here
          <div>Loading...</div>
        )}
      </body>
    </html>
  );
}

